# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TileLayer
                                 A QGIS plugin
 This plugin lays tiles.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-04-25
        copyright            : (C) 2021 by Batuhan AVCI
        email                : batuhanavci@protonmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TileLayer class from file TileLayer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tile_layer import TileLayer
    return TileLayer(iface)
