# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TileLayer
                                 A QGIS plugin
 This plugin lays tiles.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-04-25
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Batuhan AVCI
        email                : batuhanavci@protonmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import qgis.core
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .tile_layer_dialog import TileLayerDialog

import math

import os.path
# Import the PyQt and QGIS libraries
from qgis.PyQt.QtCore import *
from qgis.PyQt.QtGui import *

try:
    from qgis.PyQt.QtWidgets import *
except:
    pass
from qgis.core import *

import os
import re
import binascii
import inspect
from qgis.PyQt.QtWidgets import *


class Vector2D:
    X: 0.0
    Y: 0.0

    def __init__(self, xx, yy):
        self.X = xx
        self.Y = yy


class Polygon2D:

    def __init__(self, topLeft, topRight, bottomLeft, bottomRight):
        self.VerTextA = Vector2D(bottomLeft.X, bottomLeft.Y)
        self.VerTextB = Vector2D(bottomRight.X, bottomRight.Y)
        self.VerTextC = Vector2D(topRight.X, topRight.Y)
        self.VerTextD = Vector2D(topLeft.X, topLeft.Y)


class Utils:
    def My_Range(self, start, end, step):
        while start <= end:
            yield start
            start += step

    def RotatePoint(self, pointToRotate, centerPoint, angleInDegrees):
        angleInRadians = angleInDegrees * (math.pi / 180)
        cosTheta = math.cos(angleInRadians)
        sinTheta = math.sin(angleInRadians)
        return Vector2D(
            (cosTheta * (pointToRotate.X - centerPoint.X) - sinTheta * (
                        pointToRotate.Y - centerPoint.Y) + centerPoint.X),
            (sinTheta * (pointToRotate.X - centerPoint.X) + cosTheta * (
                        pointToRotate.Y - centerPoint.Y) + centerPoint.Y)
        )

    def TextToVector2D(self, text):
        splited = text.split(',')
        return Vector2D(float(splited[0]), float(splited[1]))


class LayerWorks:
    UtilsRef = Utils()

    EPSGToUse = 0

    UpLeftPoint = Vector2D(0, 0)  # 964322.76, 4216672.64
    UpRightPoint = Vector2D(0, 0.)  # 1268515.99, 4162487.05
    DownLeftPoint = Vector2D(0, 0)  # 931870.75, 4013108.27
    DownRightPoint = Vector2D(0, 0)  # 1229529.05, 3959792.95

    DesiredXLength = 0.0
    DesiredYLength = 0.0
    AppliedXLength = 0.0
    AppliedYLength = 0.0

    CalculatedAngleInDegrees = 0
    CalculatedAngleInRadians = 0
    AngleToRotate = 0

    StraightVertices = []
    RotatedVertices = []

    RotatedPolygons = []
    FinalPolygons = []
    BorderPolygon = 0

    BorderLayer = 0

    # def Run(self, upleftpoint, uprightpoint, downleftpoint, downrightpoint, xlength, ylength):
    def Run(self):
        # Clean-up before starting
        self.StraightVertices.clear()
        self.RotatedVertices.clear()
        self.RotatedPolygons.clear()
        self.FinalPolygons.clear()

        # Now go.
        self.DoTrigonometry()
        self.LayStraightVertices()
        self.RotateLaidVertices()
        self.CreatePolygons()
        self.LayDownTheGrid()

    # Put down straight vertices.
    def DoTrigonometry(self):
        # Calculate rotation angle.
        XDiff = self.UpRightPoint.X - self.UpLeftPoint.X
        YDiff = self.UpRightPoint.Y - self.UpLeftPoint.Y
        self.CalculatedAngleInRadians = math.atan2(XDiff, YDiff)
        self.CalculatedAngleInDegrees = self.CalculatedAngleInRadians * (180.0 / math.pi)
        self.AngleToRotate = 90 - self.CalculatedAngleInDegrees

        self.AppliedXLength = self.DesiredXLength
        self.AppliedYLength = self.DesiredYLength

        # self.AppliedXLength = self.DesiredXLength / math.sin(self.CalculatedAngleInRadians)
        # self.AppliedYLength = self.DesiredYLength / math.sin(self.CalculatedAngleInRadians)

    def LayStraightVertices(self):
        for x in Utils.My_Range(self.UtilsRef, self.UpLeftPoint.X, self.UpRightPoint.X, self.AppliedXLength):
            for y in Utils.My_Range(self.UtilsRef, self.DownRightPoint.Y, self.UpLeftPoint.Y, self.AppliedYLength):
                self.StraightVertices.append(Vector2D(x, y))

    def RotateLaidVertices(self):
        for Vertex in self.StraightVertices:
            self.RotatedVertices.append(Utils.RotatePoint(self.UtilsRef, Vertex, self.UpLeftPoint, self.AngleToRotate))

    def CreatePolygons(self):

        # Update border polygon from BorderLayer.
        borderLayer = QgsProject.instance().mapLayersByName("BorderPolygon")[0]

        for feature in borderLayer.getFeatures():
            if feature.geometry().type() == QgsWkbTypes.PolygonGeometry:
                self.BorderPolygon = feature.geometry()

        for Vertex in self.RotatedVertices:
            vertA = Vertex

            unRotatedVertB = Vector2D(vertA.X + self.AppliedXLength, vertA.Y)
            unRotatedVertC = Vector2D(vertA.X + self.AppliedXLength, vertA.Y + self.AppliedYLength)
            unRotatedVertD = Vector2D(vertA.X, vertA.Y + self.AppliedYLength)

            rotatedVertB = Utils.RotatePoint(self.UtilsRef, unRotatedVertB, vertA, self.AngleToRotate)
            rotatedVertC = Utils.RotatePoint(self.UtilsRef, unRotatedVertC, vertA, self.AngleToRotate)
            rotatedVertD = Utils.RotatePoint(self.UtilsRef, unRotatedVertD, vertA, self.AngleToRotate)

            BasicRotatedPolygon = Polygon2D(vertA, rotatedVertB, rotatedVertC, rotatedVertD)
            FinalPolygon = QgsGeometry.fromPolygonXY([[QgsPointXY(vertA.X, vertA.Y),
                                                       QgsPointXY(rotatedVertB.X, rotatedVertB.Y),
                                                       QgsPointXY(rotatedVertC.X, rotatedVertC.Y),
                                                       QgsPointXY(rotatedVertD.X, rotatedVertD.Y)]])

            if (self.BorderPolygon.contains(FinalPolygon)):
                self.RotatedPolygons.append(BasicRotatedPolygon)
                self.FinalPolygons.append(FinalPolygon)

    # Creates a Vector Layer inside the program and then lays down created polygons.
    def LayDownTheGrid(self):
        uri = "polygon?crs=epsg:"+str(self.EPSGToUse)+"&field=id:integer"
        tileLayer = QgsVectorLayer(uri, "TileLayer", "memory")
        QgsProject.instance().addMapLayer(tileLayer)

        for Polygon in self.FinalPolygons:
            fet = QgsFeature()
            fet.setGeometry(Polygon)
            fet.setAttributes([1])
            tileLayer.dataProvider().addFeature(fet)

        tileLayer.updateExtents()
        tileLayer.reload()

        # Put down a border polygon layer.

    def LayDownBorderPolygon(self):
        # Border polygon. This is actually the whole map we're trying to tile-ise.
        self.BorderPolygon = QgsGeometry.fromPolygonXY([[QgsPointXY(self.DownLeftPoint.X, self.DownLeftPoint.Y),
                                                         QgsPointXY(self.DownRightPoint.X, self.DownRightPoint.Y),
                                                         QgsPointXY(self.UpRightPoint.X, self.UpRightPoint.Y),
                                                         QgsPointXY(self.UpLeftPoint.X, self.UpLeftPoint.Y)]])

        uri = "polygon?crs=epsg:"+str(self.EPSGToUse)+"&field=id:integer"
        borderLayer = QgsVectorLayer(uri, "BorderPolygon", "memory")
        QgsProject.instance().addMapLayer(borderLayer)

        fet = QgsFeature()
        fet.setGeometry(self.BorderPolygon)
        fet.setAttributes([1])
        borderLayer.dataProvider().addFeature(fet)

        borderLayer.updateExtents()
        borderLayer.reload()


class TileLayer:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'TileLayer_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Tile Layer')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('TileLayer', message)

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/tile_layer/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Lay tiles.'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Tile Layer'),
                action)
            self.iface.removeToolBarIcon(action)

    lw = LayerWorks()
    utilsRef = Utils()

    def run(self):
        """Run method that performs all the real work"""
        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = TileLayerDialog()

        self.dlg.btnCreateBorderPolygon.clicked.connect(self.UpdateParametersAndRunBorderPolygonCreator)
        self.dlg.btnCreateTiles.clicked.connect(self.UpdateParametersAndRunTileCreator)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

    def UpdateParameters(self):
        self.lw.UpLeftPoint = Utils.TextToVector2D(self.utilsRef, self.dlg.topLeftCoord.text())
        self.lw.UpRightPoint = Utils.TextToVector2D(self.utilsRef, self.dlg.topRightCoord.text())
        self.lw.DownLeftPoint = Utils.TextToVector2D(self.utilsRef, self.dlg.bottomLeftCoord.text())
        self.lw.DownRightPoint = Utils.TextToVector2D(self.utilsRef, self.dlg.bottomRightCoord.text())
        self.lw.DesiredXLength = float(self.dlg.sizeX.text())
        self.lw.DesiredYLength = float(self.dlg.sizeY.text())
        self.lw.EPSGToUse = int(self.dlg.epsgToUse.text())

    def UpdateParametersAndRunBorderPolygonCreator(self):
        self.UpdateParameters()
        self.lw.LayDownBorderPolygon()

    def UpdateParametersAndRunTileCreator(self):
        self.UpdateParameters()
        self.lw.Run()
