# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SquareLayer
                                 A QGIS plugin
 Puts a sqaure on clicked location.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-12-08
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Batuhan AVCI
        email                : batuhanavci@protonmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import qgis.core
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

import pyproj

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .square_layer_dialog import SquareLayerDialog

import math

from math import radians, cos, sin, asin, sqrt, degrees, pi, atan2
from enum import Enum
from typing import Union, Tuple

import os.path
# Import the PyQt and QGIS libraries
from qgis.PyQt.QtCore import *
from qgis.PyQt.QtGui import *

try:
    from qgis.PyQt.QtWidgets import *
except:
    pass
from qgis.core import *

import os
import re
import binascii
import inspect
from qgis.PyQt.QtWidgets import *

# region HaversineCalinti

# mean earth radius - https://en.wikipedia.org/wiki/Earth_radius#Mean_radius
_AVG_EARTH_RADIUS_KM = 6371.0088


class Unit(Enum):
    """
    Enumeration of supported units.
    The full list can be checked by iterating over the class; e.g.
    the expression `tuple(Unit)`.
    """

    KILOMETERS = 'km'
    METERS = 'm'
    MILES = 'mi'
    NAUTICAL_MILES = 'nmi'
    FEET = 'ft'
    INCHES = 'in'
    RADIANS = 'rad'
    DEGREES = 'deg'


class Direction(Enum):
    """
    Enumeration of supported directions.
    The full list can be checked by iterating over the class; e.g.
    the expression `tuple(Direction)`.
    Angles expressed in radians.
    """

    NORTH = 0
    NORTHEAST = pi * 0.25
    EAST = pi * 0.5
    SOUTHEAST = pi * 0.75
    SOUTH = pi
    SOUTHWEST = pi * 1.25
    WEST = pi * 1.5
    NORTHWEST = pi * 1.75


# Unit values taken from http://www.unitconversion.org/unit_converter/length.html
_CONVERSIONS = {
    Unit.KILOMETERS: 1.0,
    Unit.METERS: 1000.0,
    Unit.MILES: 0.621371192,
    Unit.NAUTICAL_MILES: 0.539956803,
    Unit.FEET: 3280.839895013,
    Unit.INCHES: 39370.078740158,
    Unit.RADIANS: 1 / _AVG_EARTH_RADIUS_KM,
    Unit.DEGREES: (1 / _AVG_EARTH_RADIUS_KM) * (180.0 / pi)
}


def get_avg_earth_radius(unit):
    unit = Unit(unit)
    return _AVG_EARTH_RADIUS_KM * _CONVERSIONS[unit]


def _normalize(lat: float, lon: float) -> Tuple[float, float]:
    """
    Normalize point to [-90, 90] latitude and [-180, 180] longitude.
    """
    lat = (lat + 90) % 360 - 90
    if lat > 90:
        lat = 180 - lat
        lon += 180
    lon = (lon + 180) % 360 - 180
    return lat, lon


def _ensure_lat_lon(lat: float, lon: float):
    """
    Ensure that the given latitude and longitude have proper values. An exception is raised if they are not.
    """
    if lat < -90 or lat > 90:
        raise ValueError(f"Latitude {lat} is out of range [-90, 90]")
    if lon < -180 or lon > 180:
        raise ValueError(f"Longitude {lon} is out of range [-180, 180]")


def haversine(point1, point2, unit=Unit.KILOMETERS, normalize=False):
    """ Calculate the great-circle distance between two points on the Earth surface.

    Takes two 2-tuples, containing the latitude and longitude of each point in decimal degrees,
    and, optionally, a unit of length.

    :param point1: first point; tuple of (latitude, longitude) in decimal degrees
    :param point2: second point; tuple of (latitude, longitude) in decimal degrees
    :param unit: a member of haversine.Unit, or, equivalently, a string containing the
                 initials of its corresponding unit of measurement (i.e. miles = mi)
                 default 'km' (kilometers).
    :param normalize: if True, normalize the points to [-90, 90] latitude and [-180, 180] longitude.

    Example: ``haversine((45.7597, 4.8422), (48.8567, 2.3508), unit=Unit.METERS)``

    Precondition: ``unit`` is a supported unit (supported units are listed in the `Unit` enum)

    :return: the distance between the two points in the requested unit, as a float.

    The default returned unit is kilometers. The default unit can be changed by
    setting the unit parameter to a member of ``haversine.Unit``
    (e.g. ``haversine.Unit.INCHES``), or, equivalently, to a string containing the
    corresponding abbreviation (e.g. 'in'). All available units can be found in the ``Unit`` enum.
    """

    # unpack latitude/longitude
    lat1, lng1 = point1
    lat2, lng2 = point2

    # normalize points or ensure they are proper lat/lon, i.e., in [-90, 90] and [-180, 180]
    if normalize:
        lat1, lng1 = _normalize(lat1, lng1)
        lat2, lng2 = _normalize(lat2, lng2)
    else:
        _ensure_lat_lon(lat1, lng1)
        _ensure_lat_lon(lat2, lng2)

    # convert all latitudes/longitudes from decimal degrees to radians
    lat1 = radians(lat1)
    lng1 = radians(lng1)
    lat2 = radians(lat2)
    lng2 = radians(lng2)

    # calculate haversine
    lat = lat2 - lat1
    lng = lng2 - lng1
    d = sin(lat * 0.5) ** 2 + cos(lat1) * cos(lat2) * sin(lng * 0.5) ** 2

    return 2 * get_avg_earth_radius(unit) * asin(sqrt(d))


def haversine_vector(array1, array2, unit=Unit.KILOMETERS, comb=False, normalize=False):
    '''
    The exact same function as "haversine", except that this
    version replaces math functions with numpy functions.
    This may make it slightly slower for computing the haversine
    distance between two points, but is much faster for computing
    the distance between two vectors of points due to vectorization.
    '''
    try:
        import numpy
    except ModuleNotFoundError:
        return 'Error, unable to import Numpy,\
        consider using haversine instead of haversine_vector.'

    # ensure arrays are numpy ndarrays
    if not isinstance(array1, numpy.ndarray):
        array1 = numpy.array(array1)
    if not isinstance(array2, numpy.ndarray):
        array2 = numpy.array(array2)

    # ensure will be able to iterate over rows by adding dimension if needed
    if array1.ndim == 1:
        array1 = numpy.expand_dims(array1, 0)
    if array2.ndim == 1:
        array2 = numpy.expand_dims(array2, 0)

    # Asserts that both arrays have same dimensions if not in combination mode
    if not comb:
        if array1.shape != array2.shape:
            raise IndexError(
                "When not in combination mode, arrays must be of same size. If mode is required, use comb=True as argument.")

    # normalize points or ensure they are proper lat/lon, i.e., in [-90, 90] and [-180, 180]
    if normalize:
        array1 = numpy.array([_normalize(p[0], p[1]) for p in array1])
        array2 = numpy.array([_normalize(p[0], p[1]) for p in array2])
    else:
        [_ensure_lat_lon(p[0], p[1]) for p in array1]
        [_ensure_lat_lon(p[0], p[1]) for p in array2]

    # unpack latitude/longitude
    lat1, lng1 = array1[:, 0], array1[:, 1]
    lat2, lng2 = array2[:, 0], array2[:, 1]

    # convert all latitudes/longitudes from decimal degrees to radians
    lat1 = numpy.radians(lat1)
    lng1 = numpy.radians(lng1)
    lat2 = numpy.radians(lat2)
    lng2 = numpy.radians(lng2)

    # If in combination mode, turn coordinates of array1 into column vectors for broadcasting
    if comb:
        lat1 = numpy.expand_dims(lat1, axis=0)
        lng1 = numpy.expand_dims(lng1, axis=0)
        lat2 = numpy.expand_dims(lat2, axis=1)
        lng2 = numpy.expand_dims(lng2, axis=1)

    # calculate haversine
    lat = lat2 - lat1
    lng = lng2 - lng1
    d = (numpy.sin(lat * 0.5) ** 2
         + numpy.cos(lat1) * numpy.cos(lat2) * numpy.sin(lng * 0.5) ** 2)

    return 2 * get_avg_earth_radius(unit) * numpy.arcsin(numpy.sqrt(d))


def inverse_haversine(point, distance, direction: Union[Direction, float], unit=Unit.KILOMETERS):
    lat, lng = point
    lat, lng = map(radians, (lat, lng))
    d = distance
    r = get_avg_earth_radius(unit)
    brng = direction.value if isinstance(direction, Direction) else direction

    return_lat = asin(sin(lat) * cos(d / r) + cos(lat)
                      * sin(d / r) * cos(brng))
    return_lng = lng + atan2(sin(brng) * sin(d / r) *
                             cos(lat), cos(d / r) - sin(lat) * sin(return_lat))

    return_lat, return_lng = map(degrees, (return_lat, return_lng))
    return return_lat, return_lng


# endregion


class Vector2D:
    X: 0.0
    Y: 0.0

    def __init__(self, xx, yy):
        self.X = xx
        self.Y = yy


class Utils:

    def TextToVector2D(self, text):
        splited = text.split(',')
        return Vector2D(float(splited[0]), float(splited[1]))

    def Convert3857to4326(self, x, y):
        epsg3857 = pyproj.Proj(init='epsg:3857')
        epsg4326 = pyproj.Proj(init='epsg:4326')

        # convert the coordinates
        lon, lat = pyproj.transform(epsg3857, epsg4326, x, y)

        # print the converted coordinates
        return lon, lat

    def Convert4326to3857(self, lon, lat):
        epsg3857 = pyproj.Proj(init='epsg:3857')
        epsg4326 = pyproj.Proj(init='epsg:4326')

        # convert the coordinates
        x, y = pyproj.transform(epsg4326, epsg3857, lon, lat)

        # print the converted coordinates
        return x, y


class SquareWorks:
    UtilsRef = Utils()

    EPSGToUse = 0

    CenterPoint = Vector2D(0, 0)

    UpLeftPoint = Vector2D(0, 0)  # 964322.76, 4216672.64
    UpRightPoint = Vector2D(0, 0)  # 1268515.99, 4162487.05
    DownLeftPoint = Vector2D(0, 0)  # 931870.75, 4013108.27
    DownRightPoint = Vector2D(0, 0)  # 1229529.05, 3959792.95

    DesiredLength = 0.0

    SquarePolygon = 0
    SquareLayer = 0

    def Run(self):
        if self.EPSGToUse == 4326:
            self.CalculateSquarePolygon4326()
        elif self.EPSGToUse == 3857:
            # self.CalculateSquarePolygon3857()
            self.CalculateSquarePolygon3857DUMBWAY()

        self.LayDownSquarePolygon()

    def CalculateSquarePolygon4326(self):
        haversineDistance = sqrt((self.DesiredLength ** 2) / 2)
        point = (self.CenterPoint.X, self.CenterPoint.Y)

        resNE = inverse_haversine(point, haversineDistance, Direction.NORTHEAST)
        self.UpRightPoint = Vector2D(resNE[1], resNE[0])

        resSE = inverse_haversine(point, haversineDistance, Direction.SOUTHEAST)
        self.DownRightPoint = Vector2D(resSE[1], resSE[0])

        resSW = inverse_haversine(point, haversineDistance, Direction.SOUTHWEST)
        self.DownLeftPoint = Vector2D(resSW[1], resSW[0])

        resNW = inverse_haversine(point, haversineDistance, Direction.NORTHWEST)
        self.UpLeftPoint = Vector2D(resNW[1], resNW[0])

    def CalculateSquarePolygon3857(self):
        epsg3857 = pyproj.Proj(init='epsg:3857')

        # define the coordinate to modify
        x = self.CenterPoint.X
        y = self.CenterPoint.Y

        lat, lon = pyproj.transform(epsg3857, 'epsg:4326', x, y)
        # lon, lat = pyproj.transform(epsg3857, 'epsg:4326', x, y)

        latDiff = 2500 / 111111  # add 5000 meters to latitude
        lonDiff = 2500 / 111111  # add 5000 meters to longitude

        finalLon = lon + lonDiff
        finalLat = lat + latDiff
        resX, resY = pyproj.transform('epsg:4326', epsg3857, finalLon, finalLat)
        self.UpRightPoint = Vector2D(resX, resY)

        finalLon = lon + lonDiff
        finalLat = lat - latDiff
        resX, resY = pyproj.transform('epsg:4326', epsg3857, finalLon, finalLat)
        self.DownRightPoint = Vector2D(resX, resY)

        finalLon = lon - lonDiff
        finalLat = lat - latDiff
        resX, resY = pyproj.transform('epsg:4326', epsg3857, finalLon, finalLat)
        self.DownLeftPoint = Vector2D(resX, resY)

        finalLon = lon - lonDiff
        finalLat = lat + latDiff
        resX, resY = pyproj.transform('epsg:4326', epsg3857, finalLon, finalLat)
        self.UpLeftPoint = Vector2D(resX, resY)

        # lon, lat = Utils.Convert3857to4326(self.UtilsRef, self.CenterPoint.X, self.CenterPoint.Y)
        # self.CenterPoint = Vector2D(lon, lat)
        # self.CalculateSquarePolygon4326()
        #
        # x, y = Utils.Convert4326to3857(self.UtilsRef, lon, lat)
        # # self.UpRightPoint = Vector2D(pointX + half, pointY + half)
        # # self.DownRightPoint = Vector2D(pointX + half, pointY - half)
        # # self.DownLeftPoint = Vector2D(pointX - half, pointY - half)
        # # self.UpLeftPoint = Vector2D(pointX - half, pointY + half)

    def CalculateSquarePolygon3857DUMBWAY(self):
        pointX = self.CenterPoint.X
        pointY = self.CenterPoint.Y
        toKm = self.DesiredLength * 1000
        half = toKm / 2

        self.UpRightPoint = Vector2D(pointX + half, pointY + half)
        self.DownRightPoint = Vector2D(pointX + half, pointY - half)
        self.DownLeftPoint = Vector2D(pointX - half, pointY - half)
        self.UpLeftPoint = Vector2D(pointX - half, pointY + half)

    def LayDownSquarePolygon(self):
        self.SquarePolygon = QgsGeometry.fromPolygonXY([[QgsPointXY(self.DownLeftPoint.X, self.DownLeftPoint.Y),
                                                         QgsPointXY(self.DownRightPoint.X, self.DownRightPoint.Y),
                                                         QgsPointXY(self.UpRightPoint.X, self.UpRightPoint.Y),
                                                         QgsPointXY(self.UpLeftPoint.X, self.UpLeftPoint.Y)]])

        uri = "polygon?crs=epsg:" + str(self.EPSGToUse) + "&field=id:integer"
        SquareLayer = QgsVectorLayer(uri, "SquarePolygon", "memory")
        QgsProject.instance().addMapLayer(SquareLayer)

        fet = QgsFeature()
        fet.setAttributes([1])
        fet.setGeometry(self.SquarePolygon)
        SquareLayer.dataProvider().addFeature(fet)

        SquareLayer.updateExtents()
        SquareLayer.reload()


class SquareLayer:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'SquareLayer_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Square Layer')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('SquareLayer', message)

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/square_layer/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Square Layer'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Square Layer'),
                action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = SquareLayerDialog()

        self.dlg.btnLaySquare.clicked.connect(self.UpdateParametersAndRunSquarePolygonCreator)
        self.dlg.btnDebug.clicked.connect(self.DebugFunction)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

    def UpdateParameters(self, sw, utilsRef):
        sw.CenterPoint = Utils.TextToVector2D(utilsRef, self.dlg.centerCoord.text())
        sw.DesiredLength = float(self.dlg.size.text())
        sw.EPSGToUse = int(self.dlg.epsgToUse.text())

    def UpdateParametersAndRunSquarePolygonCreator(self):
        sw = SquareWorks()
        utilsRef = Utils()

        self.UpdateParameters(sw, utilsRef)
        sw.Run()

    # print(
    #     f"UPLEFT: {self.sw.UpLeftPoint} - UPRight: {self.sw.UpRightPoint} - Downleft: {self.sw.DownLeftPoint} - downright: {self.sw.DownRightPoint}")

    # 3489585 East | 4893470 North
    # 31.34747 East | 40.18917 North

    def DebugFunction(self):
        print("debug")
        x = 3489585
        y = 4893470
        source = (x, y)

        sonuc = Utils.Convert3857to4326(self.utilsRef, x, y)

        print(f"sonucX: {sonuc[0]} - sonucY: {sonuc[1]}")
